services:
  ci-tools:
    image: ci-tools:local
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        SHFMT_VERSION: ${SHFMT_VERSION}
        SHFMT_SHA256_AMD64: ${SHFMT_SHA256_AMD64}
        SHFMT_SHA256_ARM64: ${SHFMT_SHA256_ARM64}
        ACTIONLINT_VERSION: ${ACTIONLINT_VERSION}
        ACTIONLINT_SHA256_AMD64: ${ACTIONLINT_SHA256_AMD64}
        ACTIONLINT_SHA256_ARM64: ${ACTIONLINT_SHA256_ARM64}
        HADOLINT_VERSION: ${HADOLINT_VERSION}
        HADOLINT_SHA256_AMD64: ${HADOLINT_SHA256_AMD64}
        HADOLINT_SHA256_ARM64: ${HADOLINT_SHA256_ARM64}
        MARKDOWNLINT_CLI2_VERSION: ${MARKDOWNLINT_CLI2_VERSION}
        BIOME_VERSION: ${BIOME_VERSION}
        LUACHECK_VERSION: ${LUACHECK_VERSION}
